version: '3'

services:
  migration:
    build: .
    depends_on:
      - postgres
    environment:
      TESTE: 'TESTE'
    volumes:
      - shared-volume:/opt
    networks:
      default:
        ipv4_address: 172.80.160.8
  
  postgres:
    image: postgres:14
    ports:
      - "5444:5432"
    command:  postgres -c max_wal_size=3GB
    volumes:
      - ./sansys_db/backup/sansys_papakura_base_20230321_1800.sql:/docker-entrypoint-initdb.d/sansys_papakura_base_20230321_1800.sql #papakura
      - postgres-db-volume2:/var/lib/postgresql/data
      - ./sansys_db/backup:/var/lib/postgresql/backup
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 5s
    #   retries: 5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: adminbd
      POSTGRES_DB: sansys_template
    restart: always
    networks:
      default:
        ipv4_address: 172.80.160.2

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.80.160.0/24
          gateway: 172.80.160.1
volumes:
  shared-volume:
  postgres-db-volume2:
