dbt_veolia1:
  target: prod
  outputs:
    prod:
      type: sqlserver
      database: papakura_20220324
      driver: 'ODBC Driver 17 for SQL Server'
      server: '172.30.1.29'
      port: 1434
      schema: dbo
      user: sa
      password: 'MKlTdxuAM3EaU30pOms5YDOWK1PpmMpz'
      threads: 8
    dev:
      type: sqlserver
      database: papakura_20210504
      driver: 'ODBC Driver 17 for SQL Server'
      server: '172.30.1.146'
      port: 5434
      schema: dbo
      user: sa
      password: 'Pass@word'
      threads: 8