version: 2

models:
  - name: fat_fatura
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: ref('stage_fat_fatura')
    columns:
    - name: nr_fatura
      tests:
        - dbt_expectations.expect_column_values_to_be_unique
            