WITH INTERM AS (SELECT C.*, ROW_NUMBER() OVER(PARTITION BY C.CINSTALL ORDER BY CONSUMERNO DESC)  AS RN FROM {{source('papakura','CONSUMER')}} C

WHERE CSTATUSTYPE <> 30)

,FINAL AS(select *,1 AS RN from {{source('papakura','CONSUMER')}} WHERE CSTATUSTYPE = 30
UNION

SELECT * FROM INTERM WHERE RN =1 )

SELECT F.CACCT, F.CINSTALL, F.CONSUMERNO  FROM FINAL F
