


-- cliente + instalação(cad_unidade_comercial)
-- ROW ID_CLIENTE_UNIDADE_COMERCIAL

SELECT
null as DT_VALIDADE,
CASE WHEN CONS.CSTATUSTYPE = 30 THEN 1 ELSE 0 END as CH_ATIVO,
CONS.CACCT as CH_CLIENTE,
2 as CH_TIPO_CLIENTE,
CONS.CINSTALL as CH_MATRICULA_UNIDADE,
null as ID_SERVICO,
CONCAT('FORMER CONSUMER NO. ',CONS.CONSUMERNO) as NM_IDENTIFICACAO_UNIDADE,
cast(0 as BIT) as FL_PREFERENCIAL
FROM {{source('papakura','CONSUMER')}} CONS
