with 
CONSUMER_INTERM as (
    select *, 
    ROW_NUMBER() OVER(PARTITION BY CONS.CINSTALL ORDER BY CONS.CONSUMERNO) AS RN 
    from  {{source('papakura','CONSUMER')}} CONS)
,CONSUMER_FINAL_INTERM AS (SELECT * FROM CONSUMER_INTERM WHERE RN =1)

,CONSUMER_FINAL_INTERM2 AS (SELECT C.CONSUMERNO, C.CINSTALL, C.CACCT,L.LOCA_ITEMID,L2.LOCA_ITEMID as LOCA_ITEMID2, CASE WHEN L.full_road_name2 = L2.full_road_name2 THEN 0 
ELSE 1 END AS HAS_ALT

FROM CONSUMER_FINAL_INTERM C
LEFT JOIN {{ref('stage_loc_adj_adj')}} L ON L.LOCA_ITEMID  = C.CINSTALL
LEFT JOIN {{ref('stage_loc_adj_adj')}} L2 ON L2.LOCA_ITEMID  = C.CACCT)

,CONSUMER_FINAL AS (SELECT * FROM CONSUMER_FINAL_INTERM2 WHERE HAS_ALT = 1)


select * from CONSUMER_FINAL