WITH 
TARCHARGE AS (SELECT TC.*,

CASE 
	WHEN TC.TARC$CODE       NOT 
	IN (SELECT DISTINCT CRAT$CODE FROM TARRATE)
	THEN TC.TARC$TEMPLATE ELSE TC.TARC$CODE 
END AS TARC$CODE2



FROM {{source('papakura','TARCHARGE')}} TC
)

, BASE AS (
SELECT ECPR.ECPLAN_KEY,ECPR.ECPLAN_TARCODE AS TARCODE, 
CASE 
    WHEN ECP.ECPLAN_DESC LIKE '%Residential%' OR ECP.ECPLAN_DESC LIKE '%Domestic%' THEN 1 
    ELSE 2 
END as CH_CATEGORIA_TARIFA
FROM {{source('papakura','EMS_CON_PLAN')}} ECP
INNER JOIN {{source('papakura','EMS_CON_PLAN#REGISTER_LIST')}} ECPR ON ECPR.ECPLAN_KEY = ECP.ECPLAN_KEY

UNION

SELECT ECPF.ECPLAN_KEY,ECPF.ECPLAN_FCHGCODE  AS TARCODE, 
CASE 
    WHEN ECP.ECPLAN_DESC LIKE '%Residential%' OR ECP.ECPLAN_DESC LIKE '%Domestic%' THEN 1 
    ELSE 2 
END as CH_CATEGORIA_TARIFA

FROM {{source('papakura','EMS_CON_PLAN')}} ECP
INNER JOIN {{source('papakura','EMS_CON_PLAN#FIXED_LIST')}} ECPF ON ECPF.ECPLAN_KEY = ECP.ECPLAN_KEY
)
, TARIFA AS (SELECT BASE.*,
CASE 
    WHEN TC.TARC$TEMPLATE = 'SVOL' OR TC.TARC$TEMPLATE = 'SVOL0' THEN CASE 
        WHEN TC.TARC$UNITS IS NULL AND TC.TARC$CODE NOT IN ('SSERV0','STREA0','SVOL0','WSERV0','WSUPP0','WVOL0') THEN 1
        WHEN TC.TARC$UNITS IS NULL AND TC.TARC$CODE IN ('SSERV0','STREA0','SVOL0','WSERV0','WSUPP0','WVOL0') THEN 0
        ELSE TC.TARC$UNITS
        END * 100
    ELSE NULL 
END AS SVOL_PERC,
CASE 
    WHEN TC.TARC$TEMPLATE = 'SSERV' OR TC.TARC$TEMPLATE = 'SSERV0' THEN CASE 
    WHEN TC.TARC$UNITS IS NULL AND TC.TARC$CODE NOT IN ('SSERV0','STREA0','SVOL0','WSERV0','WSUPP0','WVOL0') THEN 1
    WHEN TC.TARC$UNITS IS NULL AND TC.TARC$CODE IN ('SSERV0','STREA0','SVOL0','WSERV0','WSUPP0','WVOL0') THEN 0
    ELSE TC.TARC$UNITS
END * 100
    ELSE NULL 
END AS SSERV_PERC,
CASE 
    WHEN TC.TARC$TEMPLATE = 'STREA' OR TC.TARC$TEMPLATE = 'STREA0' THEN CASE 
    WHEN TC.TARC$UNITS IS NULL AND TC.TARC$CODE NOT IN ('SSERV0','STREA0','SVOL0','WSERV0','WSUPP0','WVOL0') THEN 1
    WHEN TC.TARC$UNITS IS NULL AND TC.TARC$CODE IN ('SSERV0','STREA0','SVOL0','WSERV0','WSUPP0','WVOL0') THEN 0
    ELSE TC.TARC$UNITS
END * 100
    ELSE NULL 
END AS STREA_PERC,
CASE 
    WHEN TC.TARC$UNITS IS NULL AND TC.TARC$CODE NOT IN ('SSERV0','STREA0','SVOL0','WSERV0','WSUPP0','WVOL0') THEN 1
    WHEN TC.TARC$UNITS IS NULL AND TC.TARC$CODE IN ('SSERV0','STREA0','SVOL0','WSERV0','WSUPP0','WVOL0') THEN 0
    ELSE TC.TARC$UNITS
END * 100 AS ESGOTO_PORCENTAGEM,
TR.CRAT$DATE AS TAB_TARIFARIA_INICIO,
TR.CRAT$RATE/1000000 AS  VL_TARIFA,
CASE WHEN TC.TARC$TEMPLATE = 'SSERV' THEN TR.CRAT$RATE ELSE NULL END AS SSERV,
CASE WHEN TC.TARC$TEMPLATE = 'STREA' THEN TR.CRAT$RATE ELSE NULL END AS STREA,
CASE WHEN TC.TARC$TEMPLATE = 'SVOL' THEN TR.CRAT$RATE ELSE NULL END AS SVOL
FROM BASE
INNER JOIN TARCHARGE TC ON TC.TARC$CODE = BASE.TARCODE 
INNER JOIN {{source('papakura','TARRATE')}} TR ON TR.CRAT$CODE = TC.TARC$CODE2 
WHERE TC.TARC$INV$HEAD$GRP <> 'WATER' and  TC.TARC$INV$HEAD$GRP <> 'OTHER')

SELECT ECPLAN_KEY, 
CASE 
    WHEN YEAR(TAB_TARIFARIA_INICIO) >= 2014  AND SUM(SVOL) IS NULL THEN SUM(COALESCE(SSERV,0) + COALESCE(STREA,0)) + 2030000.000000 
    ELSE SUM(COALESCE(SSERV,0) + COALESCE(STREA,0)) 
END AS SSERV_STREA, 
SUM(SVOL) AS SVOL,
TAB_TARIFARIA_INICIO
FROM TARIFA
GROUP BY ECPLAN_KEY,TAB_TARIFARIA_INICIO