with
REGISTERS_INTERM as (select GBIR.*,
ROW_NUMBER() OVER(PARTITION BY GBIR.GBIINVOICE ORDER BY VMC DESC)  AS RN from GBINVOICE#REGISTERS GBIR)

,REGISTERS AS(SELECT * FROM REGISTERS_INTERM WHERE RN=1)

select * from REGISTERS
