WITH SEL AS (select G.*, VALUE AS PARAMETROS  from GBIACCRUAL G CROSS APPLY STRING_SPLIT(G.GBILOCN_ADDR,','))

,base AS (SELECT SEL.*, VALUE AS TIPO_LOGRADOURO,
CASE 
	WHEN ISNUMERIC(VALUE) = 1 THEN 'NUMERO'
	WHEN ISNUMERIC(VALUE) = 0 AND value in ('AVE','BD','CL','CT','CR','DR','LN','PL','RD','ST','TCE') THEN 'TIPO_LOGRADOURO' 
	ELSE 'LOGRADOURO'
END AS TIPO




FROM SEL CROSS APPLY STRING_SPLIT(SEL.PARAMETROS,' '))



select GBIINSTALL,TIPO_LOGRADOURO from base
WHERE TIPO = 'TIPO_LOGRADOURO'