{{config({
        "materialized": 'table',
        "post-hook": ["{{ create_nonclustered_index(columns = ['ID_PAGAMENTO_DOCUMENTO',], ) }}", ]})}}

SELECT
ROW_NUMBER() OVER(ORDER BY AP.ID_PAGAMENTO) as ID_PAGAMENTO_DOCUMENTO,
AP.VL_VALOR_DEBITO as VL_PAGAMENTO,
AP.DT_PAGAMENTO_DEBITO as DT_PAGAMENTO,
AP.MIG_ID_FATURA as ID_FATURA,
NULL as ID_COBRANCA_DIVERSA,
AP.ID_PAGAMENTO as ID_PAGAMENTO,
NULL as ID_VALOR_DEVOLVIDO,
MIG_ID_CONTA_CORRENTE_MOVIMENTACAO_TEMP as ID_CONTA_CORRENTE_MOVIMENTACAO,
AP.DT_INCLUSAO_SISTEMA as DT_INCLUSAO_SISTEMA
FROM
{{ref('arr_pagamento')}} AP