SELECT
ROW_NUMBER() OVER(ORDER BY CA.CONSUMERNO) as ID_UNIDADE_ALERTA,
coalesce(concat(CCODE.PKEY,' - ',CCODE.PDESC), 'STRING') as DS_ALERTA,
coalesce(cast(1 as BIT), cast(1 as BIT)) as FL_ATIVO,
cast(getdate() as varchar) as DT_CADASTRO_ALERTA,
null as DT_INATIVACAO_ALERTA,
CUC.CH_MATRICULA_UNIDADE as CH_MATRICULA_UNIDADE,
1 as ID_USUARIO_CADASTRO,
null as ID_USUARIO_INATIVACAO,
cast(1 as BIT) as FL_EXIBE_JTECH_OS,
cast(1 as BIT) as FL_EXIBE_SANSYS_LEITURA
FROM
{{source('papakura','CONSUMER')}} CA
INNER JOIN {{ref('cad_unidade_comercial')}} CUC ON CUC.CH_MATRICULA_UNIDADE = CA.CINSTALL
LEFT JOIN {{source('papakura','CRITICAL_CODE')}} CCODE ON CCODE.PKEY = CA.CCRITICALCODE
WHERE CA.CCRITICALCODE IS NOT NULL