{{config({
        "materialized": 'table',
        "post-hook": ["{{ create_nonclustered_index(columns = ['ID_ENDERECO_CLIENTE',], ) }}", ]})}}


WITH LOCADDRESS_ADJ_INTERM AS (SELECT *,ROW_NUMBER() OVER(PARTITION BY LOCA_ITEMID ORDER BY SEQNO DESC) AS RN FROM {{ref('LOCADDRESS_ADJ')}})

,LOCADDRESS_ADJ_ADJ as (SELECT * FROM LOCADDRESS_ADJ_INTERM WHERE RN = 1)


SELECT
ROW_NUMBER() over(order by CC.CH_CLIENTE) AS ID_ENDERECO_CLIENTE,
CE.ID_ENDERECO  AS ID_ENDERECO,
CC.CH_CLIENTE AS CH_CLIENTE,
1 AS CH_TIPO_ENDERECO,
case 
when L.LOCA_HOUSEPREFIX is not null then CONCAT(L.LOCA_HOUSEPREFIX,
                                                case when L.LOCA_UNIT IS NOT NULL THEN CONCAT('/',L.LOCA_UNIT) ELSE NULL END
,case when L.LOCA_HOUSE IS NOT NULL THEN CONCAT('/',L.LOCA_HOUSE) ELSE NULL END
,case when L.LOCA_HOUSETO IS NOT NULL THEN CONCAT('-',L.LOCA_HOUSETO) ELSE NULL END
,case when L.LOCA_HOUSESUFFIX IS NOT NULL THEN CONCAT('/',L.LOCA_HOUSESUFFIX) ELSE NULL END
) 
when L.LOCA_UNIT IS NOT NULL AND L.LOCA_HOUSEPREFIX  IS NULL THEN CONCAT('/',L.LOCA_HOUSE,case when L.LOCA_HOUSETO IS NOT NULL THEN CONCAT('-',L.LOCA_HOUSETO) ELSE NULL END,case when L.LOCA_HOUSESUFFIX IS NOT NULL THEN CONCAT('/',L.LOCA_HOUSESUFFIX) ELSE NULL END
)
else case when L.LOCA_HOUSESUFFIX IS NOT NULL THEN CONCAT('/',L.LOCA_HOUSESUFFIX) ELSE NULL END END  as  DS_COMPLEMENTO_ENDERECO,
L.SEQNO AS MIG_PK_TEMP
FROM {{ref('cad_cliente')}} CC
INNER JOIN LOCADDRESS_ADJ_ADJ L ON L.LOCA_ITEMID = CC.CH_CLIENTE
LEFT JOIN {{ref('cad_endereco')}} CE ON CE.ACTID = L.SEQNO
