SELECT
row_number() over(order by FF.ID_FATURA) as ID_FATURA_DEBITO_CONTA,
FF.ID_FATURA as ID_FATURA,
FDC.ID_DEBITO_CONTA as ID_DEBITO_CONTA,
cast(0 as BIT) as FL_CANCELAMENTO,
NULL as DT_ENVIO_CANCELAMENTO,
NULL as ID_COBRANCA_DIVERSA
FROM
{{ref('stage_fat_fatura')}} FF
INNER JOIN {{source('papakura','GBINVOICE')}} GBI ON GBI.GBIINVOICE = FF.MIG_PK_TEMP
INNER JOIN {{source('papakura','DEBT')}} DEBT ON DEBT.DSTATEMENT = GBI.GBISTATEMENT_NO
INNER JOIN {{source('papakura','LPTRAN_BANK#LPBK$PAY')}} LPBLP ON LPBLP.LPBK$DEBTID = DEBT.DKEY
INNER JOIN {{source('papakura','LPTRAN_BANK')}} LPB ON LPB.LPBK$ID = LPBLP.LPBK$ID
inner join {{ref('fat_debito_conta')}} FDC on FDC.MIG_PK_TEMP = LPBLP.LPBK$LEDGER AND FDC.MIG_LPT$BANKACCT_TEMP=LPB.LPBK$BANKACCT
where FDC.CH_ATIVO =1
GROUP BY FF.ID_FATURA,FDC.ID_DEBITO_CONTA
