WITH CONTRATO AS (SELECT * FROM TARCHARGE
WHERE TARC$CODE IN(select DISTINCT ECPfL.ECPLAN_FCHGCODE from EMS_CON_PLAN#FIXED_LIST ECPFL
))

SELECT
ROW_NUMBER() OVER(ORDER BY TARC$CODE) +100 as ID_CONTRATO,
TARC$DESC as DS_CONTRATO,
CASE 
    WHEN TARC$TEMPLATE = 'IC'
 THEN 3 else 2
END as CH_TIPO_PRESTACAO_SERVICO,
TARC$CODE as CODE,
TARC$CODE AS MIG_PK_TEMP
FROM
CONTRATO