
SELECT
row_number() over(order by FFC2.ID_FATURA)  as ID_FATURA_COMPONENTE_TABELA_TARIFARIA,
CAST(CAST(FFC.VL_AGUA_CPTE_FATURA AS VARCHAR) AS DECIMAL(16,2)) as VL_AGUA,
CAST(CAST(FFC.VL_ESGOTO_CPTE_FATURA AS VARCHAR) AS DECIMAL(16,2)) as VL_ESGOTO,
CAST(CAST(FFC.GBICSTARTDATE AS VARCHAR) AS DATE) as DT_INICIO_CONSUMO,
CAST(CAST(FFC.GBICENDDATE AS VARCHAR) AS DATE) as DT_FIM_CONSUMO,
FFC.VL_CONSUMO_CPTE_FATURA as QT_CONSUMO,
CAST(CAST(TT.ID_TARIFA AS VARCHAR) AS INTEGER) as ID_TARIFA,
CAST(FFC2.ID_FATURA_COMPONENTE AS INTEGER) as ID_FATURA_COMPONENTE,
FFC.COD_FATURA,
FFC.COD_FATURA AS MIG_PK_TEMP
FROM {{ref('stage_fat_fatura_componente')}} FFC
inner join {{ref('fat_fatura_componente')}} FFC2 ON FFC2.ID_FATURA = FFC.ID_FATURA
-- inner JOIN {{ref('fat_fatura')}} FF ON FF.ID_FATURA  = FFC2.ID_FATURA
inner JOIN {{ref('tab_tarifa')}} TT ON FFC.ID_TABELA_TARIFARIA  = TT.ID_TABELA_TARIFARIA  AND TT.PLAN_CODE  = FFC.GBICPLANID 