{{config({
        "materialized": 'table',
        "post-hook": ["{{ create_nonclustered_index(columns = ['ID_PARCELA_SERVICO_UNIDADE',], ) }}", ]})}}


SELECT row_number() over(order by ID_SERVICO_UNIDADE) AS ID_PARCELA_SERVICO_UNIDADE, 
ID_SERVICO_UNIDADE, 
VL_TOTAL_SERVICO AS VL_PARCELA_SERVICO,  
DT_GRAVACAO_SERVICO AS DT_GERACAO_PARCELA,
cast(cast(concat(year(fat.GBIDATE),concat('-',concat(month(fat.GBIDATE),concat('-',01)))) as date) as varchar) AS DT_MESANOREF_FATURADO,  
(CASE WHEN FSU.FL_POSSUI_PARCELA_FATURAR = 'S' THEN DT_GRAVACAO_SERVICO ELSE fat.GBIDATE END) AS DT_SITUACAO_PARCELA,  
FL_POSSUI_PARCELA_FATURAR,  
FSU.MIG_ID_FATURA_TEMP ,
FSU.MIG_TARIFA_FIXA_TEMP,
FSU.MIG_GBICTRN_TYPE_TEMP,
CASE WHEN DATEPART(MONTH,FSU.MIG_GBICSTARTDATE_TEMP) = 06 AND  DATEPART(DAY,FSU.MIG_GBICSTARTDATE_TEMP) = 30 THEN DATEADD(DAY,1,FSU.MIG_GBICSTARTDATE_TEMP) ELSE FSU.MIG_GBICSTARTDATE_TEMP END as MIG_GBICSTARTDATE_TEMP,
FSU.MIG_GBICENDDATE_TEMP as MIG_GBICENDDATE_TEMP,
FSU.MIG_GBICUNITS_TEMP,
FSU.MIG_GBICPLANID_TEMP,
CAST(FSU.MIG_GBICRATE_TEMP AS DECIMAL(16,3))AS MIG_GBICRATE_TEMP,
FSU.MIG_GBICCHARGE_TEMP,
FSU.CH_MATRICULA_UNIDADE AS MIG_CH_MATRICULA_UNIDADE_TEMP,
fat.GBICONSUMER
FROM {{ref('fat_servico_unidade')}} FSU  
inner JOIN {{source('papakura','GBINVOICE')}} fat ON FSU.MIG_ID_FATURA_TEMP = fat.GBIINVOICE
