WITH REFERENCIAS AS (SELECT DISTINCT DT_MESANO_REF FROM {{ref('fat_fatura')}})



SELECT
row_number() over(order by DT_MESANO_REF asc, fgf.ID_GRUPO_FATURAMENTO)as ID_CALENDARIO_FATURAMENTO,
REFERENCIAS.DT_MESANO_REF as DT_CALENDARIO_MESANO_REF,
1  as CH_ATIVO,
fgf.ID_GRUPO_FATURAMENTO as ID_GRUPO_FATURAMENTO,
1 as CH_DEFINICAO_ESTAGIO

FROM
{{ref('fat_grupo_faturamento')}} fgf,REFERENCIAS