SELECT FF.CH_MATRICULA_UNIDADE, FF.DT_MESANO_REF AS DT_MES_REF_UNIDADE, MIN(FF.ID_FATURA) AS ID_FATURA_ORIGINAL, FCF.ID_CALENDARIO_FATURAMENTO, MAX(FF.ID_FATURA) AS ID_FATURA_ATUAL 
FROM {{ref('fat_fatura')}} FF
inner JOIN {{ref('fat_calendario_faturamento')}} FCF ON (FCF.ID_GRUPO_FATURAMENTO = FF.ID_GRUPO_FATURAMENTO AND FCF.DT_CALENDARIO_MESANO_REF = FF.DT_MESANO_REF) 
-- WHERE   1=1
--AND NOT EXISTS (SELECT 1 FROM dbo_mig.fat_unidade_comercial_referencia A WHERE A.CH_MATRICULA_UNIDADE = FF.CH_MATRICULA_UNIDADE AND A.DT_MES_REF_UNIDADE = FF.DT_MESANO_REF)
GROUP BY FF.CH_MATRICULA_UNIDADE, FF.DT_MESANO_REF, FCF.ID_CALENDARIO_FATURAMENTO 
