

SELECT
ROW_NUMBER() OVER(ORDER BY FF.ID_FATURA ) as ID_CONTA_CORRENTE_MOVIMENTACAO_FATURA,
FCCM.ID_CONTA_CORRENTE_MOVIMENTACAO as ID_CONTA_CORRENTE_MOVIMENTACAO,
FF.ID_FATURA as ID_FATURA



FROM {{ref('stage_fin_conta_corrente_movimentacao_adj')}} FCCM

inner JOIN {{ref('fat_fatura')}} FF ON FF.NR_FATURA = FCCM.INVOICE