SELECT
99 as ID_EQUIPE,
'DEFAULT' as CD_EQUIPE,
'DEFAULT' as NM_LOGIN,
null as NM_SENHA,
null as NM_SENHA2,
'2022-01-01' as DT_CADASTRO_EQUIPE,
null as CH_TIPO_EQUIPE,
1 as CH_ATIVO,
null as ID_EMPREITEIRA,
null as QT_MINIMA_FUNCIONARIOS,
null as QT_MAXIMA_FUNCIONARIOS,
null as ID_EQUIPE_PERIODO