
with model as(select em.MUKEY from {{source('papakura','EMS_MUSE')}} em )

SELECT
row_number() over(order by MUKEY ) as CH_MODELO_HIDROMETRO,
7 as NU_DIGITOS,
null as QT_LIMITE_INF,
null as QT_VASAO_NOMINAL,
null as QT_VASAO_MAXIMA,
coalesce(4, 0) as CH_TIPO_HIDROMETRO,
1 as CH_ATIVO,
8 as ID_CAPACIDADE_HIDROMETRO,
DIAMETRO.CH_DIAMETRO_HIDROMETRO as CH_DIAMETRO_HIDROMETRO,
coalesce(13, 0) as ID_MARCA_HIDROMETRO,
coalesce(1, 0) as ID_CLASSE_METROLOGICA,
10 as QT_CARACTERES,
MUKEY AS DIAMETRO,
MUKEY AS MIG_DIAMETRO_TEMP
FROM MODEL
LEFT JOIN {{ref('tab_diametro_hidrometro')}} DIAMETRO ON DIAMETRO.DIAMETRO = MODEL.MUKEY
