
with
LOCADDRESS_ADJ_INTERM AS (SELECT *,ROW_NUMBER() OVER(PARTITION BY LOCA_ITEMID ORDER BY SEQNO DESC) AS RN FROM {{ref('LOCADDRESS_ADJ')}})

,LOCADDRESS_ADJ_ADJ as (SELECT * FROM LOCADDRESS_ADJ_INTERM WHERE RN = 1)

select *  from LOCADDRESS_ADJ_ADJ